In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('advertising.csv')
df.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
Daily Time Spent on Site    1000 non-null float64
Age                         1000 non-null int64
Area Income                 1000 non-null float64
Daily Internet Usage        1000 non-null float64
Ad Topic Line               1000 non-null object
City                        1000 non-null object
Male                        1000 non-null int64
Country                     1000 non-null object
Timestamp                   1000 non-null object
Clicked on Ad               1000 non-null int64
dtypes: float64(3), int64(3), object(4)
memory usage: 78.2+ KB


In [12]:
## Select non numerical categorical column names
df=df.rename(index=str, columns={"Clicked on Ad": "Clicked_on_Ad"})
df=df.rename(index=str, columns={"Ad Topic Line": "Ad_Topic_Line"})

df.head()

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad_Topic_Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked_on_Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [13]:
print(df['Clicked_on_Ad' ].value_counts())
print("\n")


df=df.rename(columns={"nClicked_on_Ad": "Clicked_on_Ad"})

1    500
0    500
Name: Clicked_on_Ad, dtype: int64




In [18]:
X = df.drop(['Clicked_on_Ad','Ad_Topic_Line','City', 'Country', 'Timestamp' ],axis=1) ## This is the dependent variable
y=df['Clicked_on_Ad']

print(X)
print(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0) 

     Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                       68.95   35     61833.90                256.09     0
1                       80.23   31     68441.85                193.77     1
2                       69.47   26     59785.94                236.50     0
3                       74.15   29     54806.18                245.89     1
4                       68.37   35     73889.99                225.58     0
5                       59.99   23     59761.56                226.74     1
6                       88.91   33     53852.85                208.36     0
7                       66.00   48     24593.33                131.76     1
8                       74.53   30     68862.00                221.51     1
9                       69.88   20     55642.32                183.82     1
10                      47.64   49     45632.51                122.02     0
11                      83.07   37     62491.01                230.87     1
12          

In [19]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()

classifier.fit(X_train,y_train)
predictions = classifier.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[149  15]
 [  7 129]]
             precision    recall  f1-score   support

          0       0.96      0.91      0.93       164
          1       0.90      0.95      0.92       136

avg / total       0.93      0.93      0.93       300



In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=25) ## Hyperparameter
classifier.fit(X_train,y_train)
predictions = classifier.predict(X_test)


from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

from sklearn.model_selection import cross_val_score 

accuracies_rf= cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10) 
accuracies_rf_mean=accuracies_rf.mean()*100
print("Mean Accuracy:Random Forest=",accuracies_rf_mean)

accuracies_rf_std=accuracies_rf.std()*100
print("Standard Deviation:Random Forest=",accuracies_rf_std)

C:\Users\sudip\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


[[151  13]
 [  7 129]]
             precision    recall  f1-score   support

          0       0.96      0.92      0.94       164
          1       0.91      0.95      0.93       136

avg / total       0.93      0.93      0.93       300

Mean Accuracy:Random Forest= 96.4279882191701
Standard Deviation:Random Forest= 2.138536131934675


In [21]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

from sklearn.model_selection import cross_val_score 

accuracies_logistic= cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10) 
accuracies_logistic_mean=accuracies_logistic.mean()*100
print("Mean Accuracy:Random Forest=",accuracies_logistic_mean)

accuracies_logistic_std=accuracies_logistic.std()*100
print("Standard Deviation:Random Forest=",accuracies_logistic_std)

[[156   8]
 [  4 132]]
             precision    recall  f1-score   support

          0       0.97      0.95      0.96       164
          1       0.94      0.97      0.96       136

avg / total       0.96      0.96      0.96       300

Mean Accuracy:Random Forest= 96.4279882191701
Standard Deviation:Random Forest= 2.1438679912040324
